default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: habit_surprise_development


test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: habit_surprise_test


production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>